
use Books 

CREATE TABLE NEWACC(
SERIAL			INT IDENTITY(1,1) PRIMARY KEY,
UNAME			NVARCHAR(MAX),
EMAIL			NVARCHAR(MAX),
GENDER			NVARCHAR(MAX),
PASS			NVARCHAR(MAX)
)

SELECT * FROM NEWACC 

DELETE FROM NEWACC WHERE SERIAL= 2

SELECT UNAME FROM NEWACC WHERE EMAIL='sagarpatil@gmail.com' AND PASS='113'

SELECT UNAME FROM NEWACC WHERE EMAIL='patil.mayur@ssvps.ac.in' AND  PASS='mayur@123'

CREATE TABLE NEWBOOK(
SERIAL			INT IDENTITY (1,1) PRIMARY KEY,
BOOK_NAME		NVARCHAR(MAX),
AUTHOR			NVARCHAR(MAX),
CATEGORY		NVARCHAR(MAX),
NO_OF_EXCHAGE	INT,
OWNER_ID		NVARCHAR(MAX),
BOOK_SUMMARY	NVARCHAR(MAX),
BOOK_COVER		NVARCHAR(MAX)
)
 
SELECT BOOK_NAME ,AUTHOR,BOOK_SUMMARY , BOOK_COVER  FROM NEWBOOK WHERE BOOK_NAME = 'SDA' 

DELETE FROM NEWBOOK WHERE SERIAL=4